### ISSUE TITLE
Moving this Project to the ODataAuthorization library

### ISSUE THREAD

**Issue by bytefish** [ika18/ODataAuthorization.Sample#2]
I would like to move this example to the ODataAuthorization samples, it’s good to have some sample code for people to copy. 

Would you be OK with it?

It has been great  to detect the bug, that hasn’t been uncovered in Unit Tests. Although I am still unsure, why it has  slipped through. My best guess is changes from .NET 6 to .NET 7? But I am too lazy to read through the ASP.NET Core history. 🫣

**Comment by ika18** [comment]
Sure, it's fine.
